In [112]:
import pandas as pd
import unicodedata
import re
from operator import concat

In [2]:
df_saber11 = pd.read_csv(r"C:\Proyectos Personales\colombia_icfes_analytics\data_raw\resultados_icfes\Examen_Saber_11_20252.txt", sep=";")

C:\Users\estebanab\AppData\Local\Temp\ipykernel_41648\4244284656.py:1: DtypeWarning: Columns (0: cole_area_ubicacion, 1: cole_bilingue, 2: cole_calendario, 3: cole_caracter, 4: cole_depto_ubicacion, 5: cole_genero, 6: cole_jornada, 7: cole_mcpio_ubicacion, 8: cole_naturaleza, 9: cole_nombre_establecimiento, 10: cole_nombre_sede, 11: cole_sede_principal, 12: fami_numhermanos, 13: estu_comunidadcampesina, 14: estu_numhijos, 15: estu_horastrabnoremu, 16: fami_posicionhermanos, 17: estu_tiempocasaacole, 18: estu_desplazacolegio) have mixed types. Specify dtype option on import or set low_memory=False.
  df_saber11 = pd.read_csv(r"C:\Proyectos Personales\colombia_icfes_analytics\data_raw\resultados_icfes\Examen_Saber_11_20252.txt", sep=";")

In [129]:
def limpiar_columna(nombre):
    nombre = unicodedata.normalize('NFKD', nombre).encode('ascii', 'ignore').decode('utf-8')
    nombre = nombre.strip()
    nombre = re.sub(r'\s+', '_', nombre)
    nombre = nombre.replace('"', '').replace("'", '')
    return nombre.upper()

df_saber11.columns = [limpiar_columna(col) for col in df_saber11.columns]

In [130]:
df_saber11.columns

Index(['PERIODO', 'ESTU_CONSECUTIVO', 'ESTU_ESTUDIANTE', 'ESTU_TIPODOCUMENTO',
       'COLE_AREA_UBICACION', 'COLE_BILINGUE', 'COLE_CALENDARIO',
       'COLE_CARACTER', 'COLE_COD_DANE_ESTABLECIMIENTO', 'COLE_COD_DANE_SEDE',
       'COLE_COD_DEPTO_UBICACION', 'COLE_COD_MCPIO_UBICACION',
       'COLE_CODIGO_ICFES', 'COLE_DEPTO_UBICACION', 'COLE_GENERO',
       'COLE_JORNADA', 'COLE_MCPIO_UBICACION', 'COLE_NATURALEZA',
       'COLE_NOMBRE_ESTABLECIMIENTO', 'COLE_NOMBRE_SEDE',
       'COLE_SEDE_PRINCIPAL', 'DESEMP_C_NATURALES', 'DESEMP_INGLES',
       'DESEMP_LECTURA_CRITICA', 'DESEMP_MATEMATICAS',
       'DESEMP_SOCIALES_CIUDADANAS', 'ESTU_AGREGADO',
       'ESTU_COD_DEPTO_PRESENTACION', 'ESTU_COD_MCPIO_PRESENTACION',
       'ESTU_COD_RESIDE_DEPTO', 'ESTU_COD_RESIDE_MCPIO',
       'ESTU_DEDICACIONINTERNET', 'ESTU_DEDICACIONLECTURADIARIA',
       'ESTU_DEPTO_PRESENTACION', 'ESTU_DEPTO_RESIDE', 'ESTU_DISCAPACIDAD',
       'ESTU_ETNIA', 'ESTU_FECHANACIMIENTO', 'ESTU_GENERO', 'ESTU_GRADO',
       'ESTU_HORASSEMANATRABAJA', 'ESTU_INSE_INDIVIDUAL',
       'ESTU_MCPIO_PRESENTACION', 'ESTU_MCPIO_RESIDE', 'ESTU_NACIONALIDAD',
       'ESTU_NSE_ESTABLECIMIENTO', 'ESTU_NSE_INDIVIDUAL', 'ESTU_PAIS_RESIDE',
       'ESTU_PRIVADO_LIBERTAD', 'ESTU_REPITE', 'ESTU_TIENEETNIA',
       'ESTU_TIPOREMUNERACION', 'FAMI_COMECARNEPESCADOHUEVO',
       'FAMI_COMECEREALFRUTOSLEGUMBRE', 'FAMI_COMELECHEDERIVADOS',
       'FAMI_CUARTOSHOGAR', 'FAMI_EDUCACIONMADRE', 'FAMI_EDUCACIONPADRE',
       'FAMI_ESTRATOVIVIENDA', 'FAMI_NUMLIBROS', 'FAMI_PERSONASHOGAR',
       'FAMI_SITUACIONECONOMICA', 'FAMI_TIENEAUTOMOVIL',
       'FAMI_TIENECOMPUTADOR', 'FAMI_TIENECONSOLAVIDEOJUEGOS',
       'FAMI_TIENEHORNOMICROOGAS', 'FAMI_TIENEINTERNET', 'FAMI_TIENELAVADORA',
       'FAMI_TIENEMOTOCICLETA', 'FAMI_TIENESERVICIOTV',
       'FAMI_TRABAJOLABORMADRE', 'FAMI_TRABAJOLABORPADRE',
       'PERCENTIL_C_NATURALES', 'PERCENTIL_GLOBAL', 'PERCENTIL_INGLES',
       'PERCENTIL_LECTURA_CRITICA', 'PERCENTIL_MATEMATICAS',
       'PERCENTIL_SOCIALES_CIUDADANAS', 'PUNT_C_NATURALES', 'PUNT_GLOBAL',
       'PUNT_INGLES', 'PUNT_LECTURA_CRITICA', 'PUNT_MATEMATICAS',
       'PUNT_SOCIALES_CIUDADANAS', 'ESTU_GRUPOETNIA', 'FAMI_NUMHERMANOS',
       'ESTU_COMUNIDADCAMPESINA', 'ESTU_NUMHIJOS', 'ESTU_HORASTRABNOREMU',
       'FAMI_POSICIONHERMANOS', 'ESTU_TIEMPOCASAACOLE',
       'ESTU_DESPLAZACOLEGIO'],
      dtype='str')

In [ ]:
periodo
estu_tipodocumento
cole_area_ubicacion
cole_bilingue
cole_calendario
cole_caracter
cole_cod_mcpio_ubicacion
cole_codigo_icfes
cole_genero
cole_jornada
cole_naturaleza
cole_nombre_establecimiento
cole_nombre_sede
desemp_ingles
estu_fechanacimiento
estu_genero
estu_grado
punt_global
----------------------- puntajes ---------------------
punt_c_naturales
punt_ingles
punt_lectura_critica
punt_matematicas
punt_sociales_ciudadanas

In [146]:
#============================== Creación de la tabla dim_estudiante ==============================

df_dim_estudiante = df_saber11[['ESTU_CONSECUTIVO','ESTU_TIPODOCUMENTO', 'ESTU_FECHANACIMIENTO', 'ESTU_GENERO']]
df_dim_estudiante["ESTU_FECHANACIMIENTO"] = pd.to_datetime(df_dim_estudiante["ESTU_FECHANACIMIENTO"], format='%d/%m/%Y', errors='coerce')
df_dim_estudiante.rename(columns={'ESTU_CONSECUTIVO':'ESTU_ID'}, inplace=True)
df_dim_estudiante['ESTU_SK'] = range(1, len(df_dim_estudiante) + 1)
cols = ['ESTU_SK'] + [c for c in df_dim_estudiante.columns if c != 'ESTU_SK']
df_dim_estudiante = df_dim_estudiante[cols]

df_dim_estudiante.to_csv("C:\\Proyectos Personales\\colombia_icfes_analytics\\data_cleaned\\dim_estudiante.csv", index=False)

In [147]:
#============================== Creación de la tabla dim_colegio ==============================

df_dim_colegio = df_saber11[['COLE_COD_DANE_ESTABLECIMIENTO','COLE_COD_DANE_SEDE', 'COLE_CODIGO_ICFES','COLE_NOMBRE_ESTABLECIMIENTO', 'COLE_NOMBRE_SEDE', 'COLE_AREA_UBICACION', 'COLE_BILINGUE', 'COLE_CALENDARIO', 'COLE_CARACTER', 'COLE_GENERO', 'COLE_JORNADA', 'COLE_NATURALEZA']]
print(df_dim_colegio.info())
df_dim_colegio.rename(columns={'COLE_COD_DANE_SEDE':'COLE_ID'}, inplace=True)
df_dim_colegio['COLE_SK'] = range(1, len(df_dim_colegio) + 1)

cols = ['COLE_SK'] + [c for c in df_dim_colegio.columns if c != 'COLE_SK']
df_dim_colegio = df_dim_colegio[cols]

df_dim_colegio.to_csv("C:\\Proyectos Personales\\colombia_icfes_analytics\\data_cleaned\\dim_colegio.csv", index=False)

<class 'pandas.DataFrame'>
RangeIndex: 576213 entries, 0 to 576212
Data columns (total 12 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   COLE_COD_DANE_ESTABLECIMIENTO  547381 non-null  float64
 1   COLE_COD_DANE_SEDE             547381 non-null  float64
 2   COLE_CODIGO_ICFES              547287 non-null  float64
 3   COLE_NOMBRE_ESTABLECIMIENTO    547287 non-null  str
 4   COLE_NOMBRE_SEDE               547287 non-null  str
 5   COLE_AREA_UBICACION            547381 non-null  str
 6   COLE_BILINGUE                  437299 non-null  str
 7   COLE_CALENDARIO                547287 non-null  str
 8   COLE_CARACTER                  521462 non-null  str
 9   COLE_GENERO                    547287 non-null  str
 10  COLE_JORNADA                   547287 non-null  str
 11  COLE_NATURALEZA                547381 non-null  str
dtypes: float64(3), str(9)
memory usage: 52.8 MB
None

In [149]:
df_dim_colegio["COLE_ID"].unique()

array([2.47245001e+11, 1.11001109e+11, 1.11265000e+11, ...,
       2.05120800e+11, 2.05120001e+11,            nan], shape=(11918,))

In [133]:
#============================== Creación de la tabla dim_tiempo ==============================

def crear_dim_tiempo(fecha_inicio='2020-01-01', fecha_fin='2025-12-31'):
    
    # Rango de fechas diario
    fechas = pd.date_range(start=fecha_inicio, end=fecha_fin, freq='D')
    
    df_dim_tiempo = pd.DataFrame({'FECHA': fechas})
    
    # Atributos de la dimensión
    df_dim_tiempo['ANIO'] = df_dim_tiempo['FECHA'].dt.year
    df_dim_tiempo['MES'] = df_dim_tiempo['FECHA'].dt.month
    df_dim_tiempo['DIA'] = df_dim_tiempo['FECHA'].dt.day
    df_dim_tiempo['SEMESTRE'] = df_dim_tiempo['MES'].apply(lambda m: 1 if m <= 6 else 2)
    df_dim_tiempo['MES_NOMBRE'] = df_dim_tiempo['FECHA'].dt.month_name(locale='es_ES')
    df_dim_tiempo["ANIO_SEMESTER"] = df_dim_tiempo['ANIO'].astype(str) + df_dim_tiempo['SEMESTRE'].astype(str)
    # ID incremental
    df_dim_tiempo["TIEMPO_SK"] = (df_dim_tiempo['ANIO'].astype(str) + df_dim_tiempo['MES'].astype(str).str.zfill(2) + df_dim_tiempo['DIA'].astype(str).str.zfill(2)).astype(int)
    
    return df_dim_tiempo


df_dim_tiempo = crear_dim_tiempo('2020-01-01', '2025-12-31')


cols = ['TIEMPO_SK'] + [c for c in df_dim_tiempo.columns if c != 'TIEMPO_SK']
df_dim_tiempo = df_dim_tiempo[cols]

df_dim_tiempo.to_csv("C:\\Proyectos Personales\\colombia_icfes_analytics\\data_cleaned\\dim_tiempo.csv", index=False)

In [139]:
display(df_dim_tiempo.head())

   TIEMPO_SK      FECHA  ANIO  MES  DIA  SEMESTRE MES_NOMBRE ANIO_SEMESTER
0   20200101 2020-01-01  2020    1    1         1      Enero         20201
1   20200102 2020-01-02  2020    1    2         1      Enero         20201
2   20200103 2020-01-03  2020    1    3         1      Enero         20201
3   20200104 2020-01-04  2020    1    4         1      Enero         20201
4   20200105 2020-01-05  2020    1    5         1      Enero         20201

In [ ]:
#============================== Creación de la tabla fact_icfes ==============================

df_fact = df_saber11[['PERIODO','COLE_COD_DEPTO_UBICACION', 'COLE_COD_MCPIO_UBICACION','ESTU_CONSECUTIVO','COLE_COD_DANE_SEDE','COLE_CODIGO_ICFES','PUNT_C_NATURALES', 'PUNT_LECTURA_CRITICA', 'PUNT_MATEMATICAS', 'PUNT_SOCIALES_CIUDADANAS', 'PUNT_INGLES', 'PUNT_GLOBAL']]

#======== unión de claves foráneas con las dimensiones =================

df_fact = df_fact.merge(df_dim_estudiante, left_on='ESTU_CONSECUTIVO', right_on='ESTU_ID', how='left') #\
   ## .merge(df_dim_colegio, left_on='COLE_COD_DANE_SEDE', right_on='COLE_ID', how='left')

#======== Eliminar columnas inncesarias de la tabla de hechos =================

df_fact = df_fact.drop(['ESTU_CONSECUTIVO', 'COLE_COD_DANE_SEDE'], axis=1)

MemoryError: Unable to allocate 6.61 GiB for an array with shape (886709451,) and data type int64

In [142]:
display(df_fact.head())

,PERIODO,COLE_COD_DEPTO_UBICACION,COLE_COD_MCPIO_UBICACION,ESTU_CONSECUTIVO,COLE_COD_DANE_SEDE,COLE_CODIGO_ICFES,PUNT_C_NATURALES,PUNT_LECTURA_CRITICA,PUNT_MATEMATICAS,PUNT_SOCIALES_CIUDADANAS,PUNT_INGLES,PUNT_GLOBAL
0,20252,47.0,47245.0,SB11202530498262,2.472450e+11,134544.0,45,51,57,48,58.0,254
1,20252,11.0,11001.0,SB11202530422673,1.110011e+11,154047.0,53,50,49,45,46.0,245
2,20252,11.0,11001.0,SB11202530169932,1.112650e+11,718775.0,57,62,64,52,53.0,292
3,20252,5.0,5001.0,SB11202530196670,3.050010e+11,593277.0,42,49,53,39,47.0,229
4,20252,5.0,5615.0,SB11202530227027,1.056150e+11,207761.0,64,64,64,58,39.0,303

In [144]:
df_fact.info()

<class 'pandas.DataFrame'>
RangeIndex: 576213 entries, 0 to 576212
Data columns (total 12 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   PERIODO                   576213 non-null  int64
 1   COLE_COD_DEPTO_UBICACION  547381 non-null  float64
 2   COLE_COD_MCPIO_UBICACION  547381 non-null  float64
 3   ESTU_CONSECUTIVO          576213 non-null  str
 4   COLE_COD_DANE_SEDE        547381 non-null  float64
 5   COLE_CODIGO_ICFES         547287 non-null  float64
 6   PUNT_C_NATURALES          576213 non-null  int64
 7   PUNT_LECTURA_CRITICA      576213 non-null  int64
 8   PUNT_MATEMATICAS          576213 non-null  int64
 9   PUNT_SOCIALES_CIUDADANAS  576213 non-null  int64
 10  PUNT_INGLES               568186 non-null  float64
 11  PUNT_GLOBAL               576213 non-null  int64
dtypes: float64(5), int64(6), str(1)
memory usage: 52.8 MB